;DAKEFPV 2G4 1W TX
[env:tx-dakepfv-2G4-1W]
extends = env_common_tx_esp32
board = esp32dev
lib_deps = 
  makuna/NeoPixelBus@^2.8.3
  moononournation/GFX Library for Arduino @ 1.2.8
  ;mLRS/Common/thirdparty/Arduino_GFX
build_src_filter = 
  ${env_common_tx_esp32.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
  +<Common/thirdparty/tft.cpp>
build_flags = 
  ${env_common_tx_esp32.build_flags}
  -D TX_ELRS_DAKEFPV_2G4_ESP32
  

;DAKEFPV 900 2w TX
[env:tx-dakepfv-900-2W]
extends = env_common_tx_esp32
board = esp32dev
lib_deps = 
  makuna/NeoPixelBus@^2.8.3
  ; mLRS/Common/thirdparty/Arduino_GFX
  moononournation/GFX Library for Arduino @ 1.2.8
build_src_filter = 
  ${env_common_tx_esp32.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
  +<Common/thirdparty/tft.cpp>
build_flags = 
  ${env_common_tx_esp32.build_flags}
  -D TX_ELRS_DAKEFPV_900_ESP32

