
;DAKEFPV LR1121 RX 900
[env:rx-dakefpv-c3-900]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_900_ESP32C3


;DAKEFPV LR1121 RX 2400
[env:rx-dakefpv-c3-2400]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_2400_ESP32C3


;DAKEFPV LR1121 RX TD 900/2G4
[env:rx-dakefpv-lr1121-td]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_LR1121_TD_ESP32C3


;DAKEFPV LR1121 RX 915 PRO
[env:rx-dakefpv-lr1121-915-pro]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_LR1121_915PRO_ESP32C3


;DAKEFPV LR1121 RX 2G4 NANOPRO
[env:rx-dakefpv-2G4-nanopro-rx]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKE2G4_NANOPRO_LR1121_ESP32C3


;DAKEFPV LR1121 RX 2G4 SUPERDPRO
[env:rx-dakefpv-2G4-superdpro-rx]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_SUPERDPRO_2400_ESP32C3


;DAKEFPV LR1121 RX 900 SUPERDPRO
[env:rx-dakefpv-900-superdpro-rx]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_SUPERDPRO_900_ESP32C3

;DAKEFPV LR1121 900/2400 dualband pro RX
[env:rx-dakefpv-900-2400-dualband-pro-rx]
extends = env_common_rx_esp32c3
board = esp32-c3-devkitm-1
lib_deps =
  makuna/NeoPixelBus@^2.8.3
build_src_filter =
  ${env_common_rx_esp32c3.build_src_filter}
  +<modules/sx12xx-lib/src/lr11xx.cpp>
build_flags =
  ${env_common_rx_esp32c3.build_flags}
  -D RX_ELRS_DAKEFPV_LR1121_DUALBAND_PRO_ESP32C3

